In [1]:
from google.colab import files
uploaded = files.upload()

Saving Salary.csv to Salary.csv

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("Salary.csv")

# **Part1**

In [5]:
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race,Senior
0,32.0,Male,1,Software Engineer,5.0,90000.0,UK,White,0
1,28.0,Female,2,Data Analyst,3.0,65000.0,USA,Hispanic,0
2,45.0,Male,3,Manager,15.0,150000.0,Canada,White,1
3,36.0,Female,1,Sales Associate,7.0,60000.0,USA,Hispanic,0
4,52.0,Male,2,Director,20.0,200000.0,USA,Asian,0

In [6]:
df.tail()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race,Senior
6679,49.0,Female,3,Director of Marketing,20.0,200000.0,UK,Mixed,0
6680,32.0,Male,0,Sales Associate,3.0,50000.0,Australia,Australian,0
6681,30.0,Female,1,Financial Manager,4.0,55000.0,China,Chinese,0
6682,46.0,Male,2,Marketing Manager,14.0,140000.0,China,Korean,0
6683,26.0,Female,0,Sales Executive,1.0,35000.0,Canada,Black,0

In [7]:
#  Show Shape and Columns
df.shape, df.columns.tolist()

((6684, 9),
 ['Age',
  'Gender',
  'Education Level',
  'Job Title',
  'Years of Experience',
  'Salary',
  'Country',
  'Race',
  'Senior'])

In [8]:
#  Summary Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6684 entries, 0 to 6683
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6684 non-null   float64
 1   Gender               6684 non-null   object
 2   Education Level      6684 non-null   int64
 3   Job Title            6684 non-null   object
 4   Years of Experience  6684 non-null   float64
 5   Salary               6684 non-null   float64
 6   Country              6684 non-null   object
 7   Race                 6684 non-null   object
 8   Senior               6684 non-null   int64
dtypes: float64(3), int64(2), object(4)
memory usage: 470.1+ KB

In [9]:
#  Descriptive Statistics
df.describe(include='all')

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race,Senior
count,6684.000000,6684,6684.000000,6684,6684.000000,6684.000000,6684,6684,6684.000000
unique,NaN,2,NaN,129,NaN,NaN,5,10,NaN
top,NaN,Male,NaN,Software Engineer,NaN,NaN,USA,White,NaN
freq,NaN,3671,NaN,809,NaN,NaN,1356,1957,NaN
mean,33.610563,NaN,1.622382,NaN,8.077723,115307.175194,NaN,NaN,0.143477
std,7.595994,NaN,0.880474,NaN,6.029305,52806.810881,NaN,NaN,0.350585
min,21.000000,NaN,0.000000,NaN,0.000000,350.000000,NaN,NaN,0.000000
25%,28.000000,NaN,1.000000,NaN,3.000000,70000.000000,NaN,NaN,0.000000
50%,32.000000,NaN,1.000000,NaN,7.000000,115000.000000,NaN,NaN,0.000000
75%,38.000000,NaN,2.000000,NaN,12.000000,160000.000000,NaN,NaN,0.000000
max,62.000000,NaN,3.000000,NaN,34.000000,250000.000000,NaN,NaN,1.000000

In [10]:
#  Check Missing Values
df.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
Country                0
Race                   0
Senior                 0
dtype: int64

In [11]:
#  Count Duplicates
df.duplicated().sum()

np.int64(1536)

# **Part2**

In [12]:
#  Top 10 Job Titles
df['Job Title'].value_counts().head(10)

Job Title
Software Engineer            809
Data Scientist               515
Data Analyst                 391
Software Engineer Manager    376
Product Manager              323
Project Engineer             317
Marketing Manager            315
Full Stack Engineer          304
Back end Developer           242
Front end Developer          239
Name: count, dtype: int64

In [14]:
#  Selected Columns
df[['Job Title', 'Salary', 'Gender', 'Country']]

                  Job Title    Salary  Gender    Country
0         Software Engineer   90000.0    Male         UK
1              Data Analyst   65000.0  Female        USA
2                   Manager  150000.0    Male     Canada
3           Sales Associate   60000.0  Female        USA
4                  Director  200000.0    Male        USA
...                     ...       ...     ...        ...
6679  Director of Marketing  200000.0  Female         UK
6680        Sales Associate   50000.0    Male  Australia
6681      Financial Manager   55000.0  Female      China
6682      Marketing Manager  140000.0    Male      China
6683        Sales Executive   35000.0  Female     Canada

[6684 rows x 4 columns]

In [15]:
#  Filter Job Titles with "Data Scientist"
df[df['Job Title'].str.contains("Data Scientist", case=False, na=False)]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race,Senior
32,29.0,Male,2,Data Scientist,3.0,75000.0,USA,Hispanic,0
63,47.0,Male,3,Data Scientist,21.0,180000.0,China,White,1
146,42.0,Female,3,Data Scientist,16.0,150000.0,China,Chinese,1
173,26.0,Female,2,Data Scientist,1.5,45000.0,Canada,Asian,0
225,46.0,Male,3,Data Scientist,18.0,160000.0,Canada,White,1
...,...,...,...,...,...,...,...,...,...
6183,32.0,Female,3,Data Scientist,9.0,145000.0,China,Korean,0
6197,32.0,Female,3,Data Scientist,9.0,145000.0,China,White,0
6211,32.0,Female,3,Data Scientist,9.0,145000.0,UK,Asian,0
6225,32.0,Female,3,Data Scientist,9.0,145000.0,USA,Asian,0
6239,32.0,Female,3,Data Scientist,9.0,145000.0,Australia,White,0

In [18]:

# Filter Education Level with "PhD"
df[df['Education Level'] == 3] #phd

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race,Senior
2,45.0,Male,3,Manager,15.0,150000.0,Canada,White,1
9,38.0,Male,3,Scientist,10.0,110000.0,Australia,Australian,1
17,39.0,Male,3,Engineer,12.0,115000.0,UK,Mixed,1
28,43.0,Female,3,Consultant,15.0,140000.0,Canada,Black,1
34,46.0,Male,3,Manager,20.0,170000.0,USA,Hispanic,1
...,...,...,...,...,...,...,...,...,...
6662,28.0,Male,3,Marketing Manager,4.0,55000.0,Canada,Asian,0
6665,49.0,Female,3,Product Marketing Manager,20.0,200000.0,China,White,1
6671,36.0,Female,3,Marketing Manager,9.0,95000.0,China,Chinese,0
6676,28.0,Male,3,Sales Representative,4.0,55000.0,China,Korean,0
6679,49.0,Female,3,Director of Marketing,20.0,200000.0,UK,Mixed,0

In [19]:
#  Top Paid Job Titles
df[['Job Title', 'Salary']].sort_values(by='Salary', ascending=False).drop_duplicates('Job Title').head(10)

                      Job Title    Salary
30                          CEO  250000.0
4983          Financial Manager  250000.0
83     Chief Technology Officer  250000.0
4363             Data Scientist  240000.0
4379          Marketing Manager  228000.0
105          Chief Data Officer  220000.0
2650   Director of Data Science  220000.0
2202           Project Engineer  210000.0
1710  Software Engineer Manager  210000.0
6623      Director of Marketing  200000.0

In [96]:
#  High Earners (Salary > $100,000)
df[df['Salary'] > 100000]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race,Senior,IsSenior,...,GenderBin,JobType,SalaryPerYear,YearsOfExp_Normalized,Country_Australia,Country_Canada,Country_China,Country_UK,Country_USA,IsTech
2,45.0,Male,3,Manager,15.0,150000.0,Canada,White,1,0,...,0,Other,10000.000000,0.441176,False,True,False,False,False,0
4,52.0,Male,2,Director,20.0,200000.0,USA,Asian,0,0,...,0,Other,10000.000000,0.588235,False,False,False,False,True,0
6,42.0,Female,2,Product Manager,12.0,120000.0,USA,Asian,0,0,...,1,Other,10000.000000,0.352941,False,False,False,False,True,0
9,38.0,Male,3,Scientist,10.0,110000.0,Australia,Australian,1,0,...,0,Scientist,11000.000000,0.294118,True,False,False,False,False,0
11,48.0,Female,1,HR Manager,18.0,140000.0,UK,Asian,0,0,...,1,Other,7777.777778,0.529412,False,False,False,True,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6670,42.0,Male,1,Financial Manager,13.0,130000.0,Australia,Asian,0,0,...,0,Other,10000.000000,0.382353,True,False,False,False,False,0
6673,43.0,Female,2,Sales Manager,14.0,140000.0,Canada,Asian,0,0,...,1,Other,10000.000000,0.411765,False,True,False,False,False,0
6677,51.0,Female,2,Product Marketing Manager,19.0,190000.0,UK,White,1,0,...,1,Other,10000.000000,0.558824,False,False,False,True,False,0
6679,49.0,Female,3,Director of Marketing,20.0,200000.0,UK,Mixed,0,0,...,1,Other,10000.000000,0.588235,False,False,False,True,False,0
6682,46.0,Male,2,Marketing Manager,14.0,140000.0,China,Korean,0,0,...,0,Other,10000.000000,0.411765,False,False,True,False,False,0

In [21]:
#  Females in Tech Earning Above Average Salary
avg_salary = df['Salary'].mean()
df[(df['Gender'] == 'Female') &
   (df['Job Title'].str.contains("Engineer", case=False, na=False)) &
   (df['Salary'] > avg_salary)]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race,Senior
342,44.0,Female,3,Data Engineer,16.0,160000.0,Canada,Asian,1
366,44.0,Female,3,Data Engineer,16.0,160000.0,Australia,White,1
374,28.0,Female,1,Software Engineer,3.0,125000.0,Canada,Black,0
378,29.0,Female,1,Software Engineer,4.0,140000.0,Australia,White,0
382,31.0,Female,1,Software Engineer,6.0,155000.0,UK,Welsh,0
...,...,...,...,...,...,...,...,...,...
3110,36.0,Female,2,Project Engineer,12.0,130356.0,Australia,Asian,1
3114,50.0,Female,2,Software Engineer,23.0,183690.0,China,Korean,1
3118,48.0,Female,1,Project Engineer,22.0,168691.0,Australia,Asian,1
5866,32.0,Female,2,Software Engineer,9.0,120000.0,Australia,White,0
5993,33.0,Female,2,Software Engineer,8.0,120000.0,UK,Mixed,0

In [22]:
#  Clean Column Names
df.columns = df.columns.str.strip()

# Part3

In [25]:
#  Convert Salary to Numeric
df['Salary'] = df['Salary'].replace('[\$,]', '', regex=True).astype(float)
df['Salary'].head(10)

0     90000.0
1     65000.0
2    150000.0
3     60000.0
4    200000.0
5     55000.0
6    120000.0
7     80000.0
8     45000.0
9    110000.0
Name: Salary, dtype: float64

In [29]:
#  Normalize Education and Gender
df['Education Level'] = df['Education Level'].astype(str).str.title().str.strip()
df['Gender'] = df['Gender'].str.title().str.strip()
df[['Education Level', 'Gender']].head(10)

  Education Level  Gender
0               1    Male
1               2  Female
2               3    Male
3               1  Female
4               2    Male
5               1    Male
6               2  Female
7               1    Male
8               1  Female
9               3    Male

In [32]:
# Fill Missing Gender with Mode
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Gender'].isnull().sum()

np.int64(0)

In [35]:
#  Fill Missing Experience with Median
df['Years of Experience'] = df['Years of Experience'].fillna(df['Years of Experience'].median())
df['Years of Experience'].isnull().sum()

np.int64(0)

In [37]:
# Remove Extreme Salaries > 500,000
df = df[df['Salary'] <= 500000]
df['Salary'].max()

250000.0

In [38]:
#  Drop Columns with >90% Missing
threshold = len(df) * 0.9
df = df.dropna(thresh=threshold, axis=1)

In [39]:
#  Print Shape and Summary After Cleaning
df.shape, df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6684 entries, 0 to 6683
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6684 non-null   float64
 1   Gender               6684 non-null   object
 2   Education Level      6684 non-null   object
 3   Job Title            6684 non-null   object
 4   Years of Experience  6684 non-null   float64
 5   Salary               6684 non-null   float64
 6   Country              6684 non-null   object
 7   Race                 6684 non-null   object
 8   Senior               6684 non-null   int64
dtypes: float64(3), int64(1), object(5)
memory usage: 470.1+ KB

((6684, 9), None)

# **Part4**

In [43]:
#  Salary Statistics
salary_summary = pd.Series({
    'mean': df['Salary'].mean(),
    'median': df['Salary'].median(),
    'std': df['Salary'].std(),
    'min': df['Salary'].min(),
    'max': df['Salary'].max(),
    '25%': np.percentile(df['Salary'], 25),
    '75%': np.percentile(df['Salary'], 75)
})
salary_summary

mean      115307.175194
median    115000.000000
std        52806.810881
min          350.000000
max       250000.000000
25%        70000.000000
75%       160000.000000
dtype: float64

In [44]:
#  Average Salary by Gender
df.groupby('Gender')['Salary'].mean()

Gender
Female    107888.998672
Male      121395.697630
Name: Salary, dtype: float64

In [45]:
#  Highest Median Salaries by Job Title
df.groupby('Job Title')['Salary'].median().sort_values(ascending=False).head(10)

Job Title
Chief Technology Officer       250000.0
CEO                            250000.0
Chief Data Officer             220000.0
Director of Data Science       210000.0
Director                       200000.0
VP of Finance                  200000.0
Operations Director            190000.0
Marketing Director             190000.0
VP of Operations               190000.0
Director of Human Resources    187500.0
Name: Salary, dtype: float64

In [47]:
#  Pivot by country insted of indusrty  and Education
df.pivot_table(index='Country', columns='Education Level', values='Salary', aggfunc='mean')

Education Level             0             1              2              3
Country
Australia        36628.294118  95094.020000  129599.134454  167993.141304
Canada           32995.685393  94958.839041  133123.875000  167703.713208
China            33419.013158  96771.964744  129873.193906  165081.345324
UK               36592.423529  94818.807626  128487.240642  163953.692568
USA              31932.190476  93768.765723  129216.568063  163568.299213

In [48]:
#  Correlation Between Salary and Experience
df[['Salary', 'Years of Experience']].corr()

                       Salary  Years of Experience
Salary               1.000000             0.810942
Years of Experience  0.810942             1.000000

In [50]:
#  Salary Summary by Education Level
df.groupby('Education Level')['Salary'].describe()

,count,mean,std,min,25%,50%,75%,max
Education Level,,,,,,,,
0,436.0,34415.612385,16563.414595,25000.0,25000.0,30000.0,35000.0,165919.0
1,3021.0,95082.908640,44091.790154,350.0,60000.0,80000.0,122485.0,250000.0
2,1858.0,130078.384822,40649.723820,32000.0,101186.0,130000.0,160000.0,228000.0
3,1369.0,165651.457999,34339.751664,579.0,150000.0,170000.0,190000.0,250000.0

In [53]:
#  >10 Years Experience, Avg Salary by country instead od indusrty
df[df['Years of Experience'] > 10].groupby('Country')['Salary'].mean()

Country
Australia    170510.564165
Canada       169584.063529
China        167757.311060
UK           170175.503513
USA          165753.894472
Name: Salary, dtype: float64

In [54]:
#  Salary by Job Title and Gender
df.groupby(['Job Title', 'Gender'])['Salary'].mean().unstack()

Gender                          Female           Male
Job Title
Account Executive         95000.000000            NaN
Account Manager           82500.000000   60000.000000
Accountant                67500.000000   53750.000000
Administrative Assistant  50000.000000            NaN
Advertising Coordinator            NaN   45000.000000
...                                ...            ...
UX Researcher             65000.000000            NaN
VP of Finance                      NaN  200000.000000
VP of Operations                   NaN  190000.000000
Web Designer                       NaN   45000.000000
Web Developer             55964.912281   62666.666667

[129 rows x 2 columns]

In [55]:
#  Salary Std Dev by country
df.groupby('Country')['Salary'].std()

Country
Australia    53867.506931
Canada       53447.945022
China        51760.384786
UK           53049.216376
USA          51901.385767
Name: Salary, dtype: float64

# **Part5**

In [56]:
# Salaries > $120,000
df[df['Salary'] > 120000]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race,Senior
2,45.0,Male,3,Manager,15.0,150000.0,Canada,White,1
4,52.0,Male,2,Director,20.0,200000.0,USA,Asian,0
11,48.0,Female,1,HR Manager,18.0,140000.0,UK,Asian,0
13,40.0,Female,2,Project Manager,14.0,130000.0,USA,African American,0
15,44.0,Male,1,Operations Manager,16.0,125000.0,China,Chinese,0
...,...,...,...,...,...,...,...,...,...
6670,42.0,Male,1,Financial Manager,13.0,130000.0,Australia,Asian,0
6673,43.0,Female,2,Sales Manager,14.0,140000.0,Canada,Asian,0
6677,51.0,Female,2,Product Marketing Manager,19.0,190000.0,UK,White,1
6679,49.0,Female,3,Director of Marketing,20.0,200000.0,UK,Mixed,0
6682,46.0,Male,2,Marketing Manager,14.0,140000.0,China,Korean,0

In [59]:
#= Engineers with <5 Years of Experience
df[(df['Job Title'].str.contains("Engineer", case=False, na=False)) & (df['Years of Experience'] < 5)]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race,Senior
42,30.0,Male,1,Network Engineer,3.0,60000.0,China,Korean,0
159,28.0,Male,1,Software Engineer,2.0,40000.0,Australia,White,0
374,28.0,Female,1,Software Engineer,3.0,125000.0,Canada,Black,0
378,29.0,Female,1,Software Engineer,4.0,140000.0,Australia,White,0
386,29.0,Female,1,Software Engineer,4.0,140000.0,USA,Hispanic,0
...,...,...,...,...,...,...,...,...,...
6172,27.0,Male,1,Software Engineer,3.0,80000.0,USA,Asian,0
6186,27.0,Male,1,Software Engineer,3.0,80000.0,China,Korean,0
6200,27.0,Male,1,Software Engineer,3.0,80000.0,Australia,White,0
6214,27.0,Male,1,Software Engineer,3.0,80000.0,Australia,Asian,0
6228,27.0,Male,1,Software Engineer,3.0,80000.0,UK,Mixed,0

In [104]:
#has error
#  Female, marketing instead of finnace, Master's Degree
df[
    (df['Gender'] == 'Female') &
    (df['Job Title'].str.contains("Marketing", case=False, na=False)) &
    (df['Education Level'] == 2)
]

Empty DataFrame
Columns: [Age, Gender, Education Level, Job Title, Years of Experience, Salary, Country, Race, Senior, IsSenior, IsManager, ExpLevel, Salary_zscore, GenderBin, JobType, SalaryPerYear, YearsOfExp_Normalized, Country_Australia, Country_Canada, Country_China, Country_UK, Country_USA, IsTech]
Index: []

[0 rows x 23 columns]

In [73]:
# Salary < 50K and Experience >10
df[(df['Salary'] < 50000) & (df['Years of Experience'] > 10)]

Empty DataFrame
Columns: [Age, Gender, Education Level, Job Title, Years of Experience, Salary, Country, Race, Senior]
Index: []

In [76]:
# : Query – Males in software earning > $80K
df[
    (df['Gender'] == 'Male') &
    (df['Salary'] > 80000) &
    (df['Job Title'].str.contains("Engineer|Developer|Data|Software", case=False, na=False))
]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race,Senior
0,32.0,Male,1,Software Engineer,5.0,90000.0,UK,White,0
17,39.0,Male,3,Engineer,12.0,115000.0,UK,Mixed,1
37,42.0,Male,2,Project Engineer,14.0,115000.0,China,White,0
57,43.0,Male,3,Engineer,17.0,140000.0,USA,Hispanic,1
63,47.0,Male,3,Data Scientist,21.0,180000.0,China,White,1
...,...,...,...,...,...,...,...,...,...
5738,33.0,Male,2,Software Engineer,9.0,120000.0,UK,Mixed,0
5861,33.0,Male,2,Software Engineer,8.0,120000.0,Canada,White,0
5863,30.0,Male,3,Data Scientist,6.0,100000.0,UK,Asian,0
5988,34.0,Male,2,Software Engineer,9.0,125000.0,USA,African American,0
5990,31.0,Male,3,Data Scientist,7.0,110000.0,Canada,White,0

In [77]:
#PhDs earning < $90K
df[
    (df['Education Level'] == 3) &
    (df['Salary'] < 90000)
]

Empty DataFrame
Columns: [Age, Gender, Education Level, Job Title, Years of Experience, Salary, Country, Race, Senior]
Index: []

In [78]:
df[
    df['Job Title'].str.contains("Doctor|Nurse|Medical|Healthcare|Clinician", case=False, na=False)
].sort_values(by='Salary', ascending=False)

Empty DataFrame
Columns: [Age, Gender, Education Level, Job Title, Years of Experience, Salary, Country, Race, Senior]
Index: []

In [79]:
#Salary > 100K and Exp < 5
df[
    (df['Salary'] > 100000) &
    (df['Years of Experience'] < 5)
]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race,Senior
374,28.0,Female,1,Software Engineer,3.0,125000.0,Canada,Black,0
375,26.0,Male,2,Product Manager,2.0,120000.0,China,White,0
376,27.0,Female,1,Data Analyst,2.0,110000.0,UK,Mixed,0
378,29.0,Female,1,Software Engineer,4.0,140000.0,Australia,White,0
383,28.0,Male,2,Product Manager,3.0,130000.0,Canada,Black,0
...,...,...,...,...,...,...,...,...,...
2501,26.0,Male,2,Full Stack Engineer,4.0,102859.0,UK,Welsh,0
2548,24.0,Male,3,Software Engineer Manager,1.0,106132.0,Australia,Asian,0
2793,24.0,Male,3,Software Engineer Manager,1.0,106686.0,Australia,Asian,0
2911,24.0,Male,3,Software Engineer Manager,1.0,106686.0,USA,White,0
3029,24.0,Male,3,Software Engineer Manager,1.0,106686.0,Australia,Asian,0

In [81]:

#Filter Tech, Finance, Healthcare roles
df[
    df['Job Title'].str.contains("Engineer|Developer|Tech|Data|Finance|Accounting|Bank|Doctor|Nurse|Medical|Healthcare", case=False, na=False)
]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary,Country,Race,Senior
0,32.0,Male,1,Software Engineer,5.0,90000.0,UK,White,0
1,28.0,Female,2,Data Analyst,3.0,65000.0,USA,Hispanic,0
10,29.0,Male,2,Software Developer,3.0,75000.0,UK,Welsh,0
17,39.0,Male,3,Engineer,12.0,115000.0,UK,Mixed,1
18,25.0,Female,1,Data Entry Clerk,0.0,35000.0,UK,Asian,0
...,...,...,...,...,...,...,...,...,...
6211,32.0,Female,3,Data Scientist,9.0,145000.0,UK,Asian,0
6214,27.0,Male,1,Software Engineer,3.0,80000.0,Australia,Asian,0
6225,32.0,Female,3,Data Scientist,9.0,145000.0,USA,Asian,0
6228,27.0,Male,1,Software Engineer,3.0,80000.0,UK,Mixed,0
6239,32.0,Female,3,Data Scientist,9.0,145000.0,Australia,White,0

# **Part6**

In [83]:
# IsSenior Feature
df['IsSenior'] = df['Job Title'].str.contains("Senior|Sr\.|Lead|Principal", case=False, na=False).astype(int)
df[['Job Title', 'IsSenior']].head(10)

               Job Title  IsSenior
0      Software Engineer         0
1           Data Analyst         0
2                Manager         0
3        Sales Associate         0
4               Director         0
5      Marketing Analyst         0
6        Product Manager         0
7          Sales Manager         0
8  Marketing Coordinator         0
9              Scientist         0

In [85]:
#  IsManager Feature
df['IsManager'] = df['Job Title'].str.contains("Manager", case=False, na=False).astype(int)
df[['Job Title', 'IsManager']].head(10)

               Job Title  IsManager
0      Software Engineer          0
1           Data Analyst          0
2                Manager          1
3        Sales Associate          0
4               Director          0
5      Marketing Analyst          0
6        Product Manager          1
7          Sales Manager          1
8  Marketing Coordinator          0
9              Scientist          0

In [87]:
#  Experience Level Binning
def exp_level(x):
    if x < 2: return 'Entry'
    elif x < 5: return 'Junior'
    elif x < 10: return 'Mid'
    elif x < 20: return 'Senior'
    else: return 'Veteran'
df['ExpLevel'] = df['Years of Experience'].apply(exp_level)
df[['Years of Experience', 'ExpLevel']].head(10)

   Years of Experience ExpLevel
0                  5.0      Mid
1                  3.0   Junior
2                 15.0   Senior
3                  7.0      Mid
4                 20.0  Veteran
5                  2.0   Junior
6                 12.0   Senior
7                  4.0   Junior
8                  1.0    Entry
9                 10.0   Senior

In [88]:
#  Z-score Normalization
df['Salary_zscore'] = (df['Salary'] - df['Salary'].mean()) / df['Salary'].std()
df[['Salary', 'Salary_zscore']].head(10)

     Salary  Salary_zscore
0   90000.0      -0.479241
1   65000.0      -0.952665
2  150000.0       0.656976
3   60000.0      -1.047349
4  200000.0       1.603824
5   55000.0      -1.142034
6  120000.0       0.088868
7   80000.0      -0.668610
8   45000.0      -1.331404
9  110000.0      -0.100502

In [89]:
#  Gender Binary Column
df['GenderBin'] = df['Gender'].map({'Male': 0, 'Female': 1})
df[['Gender', 'GenderBin']].head(10)

   Gender  GenderBin
0    Male          0
1  Female          1
2    Male          0
3  Female          1
4    Male          0
5    Male          0
6  Female          1
7    Male          0
8  Female          1
9    Male          0

In [90]:
# JobType Column
def job_type(title):
    title = title.lower()
    if 'engineer' in title: return 'Engineer'
    elif 'scientist' in title: return 'Scientist'
    elif 'analyst' in title: return 'Analyst'
    else: return 'Other'
df['JobType'] = df['Job Title'].apply(job_type)
df[['Job Title', 'JobType']].head(10)

               Job Title    JobType
0      Software Engineer   Engineer
1           Data Analyst    Analyst
2                Manager      Other
3        Sales Associate      Other
4               Director      Other
5      Marketing Analyst    Analyst
6        Product Manager      Other
7          Sales Manager      Other
8  Marketing Coordinator      Other
9              Scientist  Scientist

In [91]:
# Salary per Year of Experience
df['SalaryPerYear'] = df['Salary'] / df['Years of Experience'].replace(0, np.nan)
df[['Salary', 'Years of Experience', 'SalaryPerYear']].head(10)

     Salary  Years of Experience  SalaryPerYear
0   90000.0                  5.0   18000.000000
1   65000.0                  3.0   21666.666667
2  150000.0                 15.0   10000.000000
3   60000.0                  7.0    8571.428571
4  200000.0                 20.0   10000.000000
5   55000.0                  2.0   27500.000000
6  120000.0                 12.0   10000.000000
7   80000.0                  4.0   20000.000000
8   45000.0                  1.0   45000.000000
9  110000.0                 10.0   11000.000000

In [105]:
#  One-hot Encode country
country_dummies = pd.get_dummies(df['Country'], prefix='Country')
df = pd.concat([df, country_dummies], axis=1)
# Show the original Country column with its new one-hot encoded columns
df[['Country'] + [col for col in df.columns if col.startswith('Country_')]].head(10)

,Country,Country_Australia,Country_Australia,Country_Canada,Country_Canada,Country_China,Country_China,Country_UK,Country_UK,Country_USA,...,Country_Australia,Country_Australia,Country_Canada,Country_Canada,Country_China,Country_China,Country_UK,Country_UK,Country_USA,Country_USA
0,UK,False,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,True,True,False,False
1,USA,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,True
2,Canada,False,False,True,True,False,False,False,False,False,...,False,False,True,True,False,False,False,False,False,False
3,USA,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,True
4,USA,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,True
5,USA,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,True
6,USA,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,True
7,China,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,True,False,False,False,False
8,China,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,True,False,False,False,False
9,Australia,True,True,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False

In [94]:
#  IsTech Binary
df['IsTech'] = df['Job Title'].str.contains("Engineer|Developer|Tech|Software|Data", case=False, na=False).astype(int)
df[['Job Title', 'IsTech']].head(10)

               Job Title  IsTech
0      Software Engineer       1
1           Data Analyst       1
2                Manager       0
3        Sales Associate       0
4               Director       0
5      Marketing Analyst       0
6        Product Manager       0
7          Sales Manager       0
8  Marketing Coordinator       0
9              Scientist       0

In [95]:
#  Normalize Years of Experience
df['YearsOfExp_Normalized'] = (df['Years of Experience'] - df['Years of Experience'].min()) / (df['Years of Experience'].max() - df['Years of Experience'].min())
df[['Years of Experience', 'YearsOfExp_Normalized']].head(10)

   Years of Experience  YearsOfExp_Normalized
0                  5.0               0.147059
1                  3.0               0.088235
2                 15.0               0.441176
3                  7.0               0.205882
4                 20.0               0.588235
5                  2.0               0.058824
6                 12.0               0.352941
7                  4.0               0.117647
8                  1.0               0.029412
9                 10.0               0.294118